"""The offshore coverage frame (FIXES item 12): one continuous boundary
around the routable world, drawn through the WATER instead of tracing
coastlines.

Why: the original per-ring dashed boundary traced every wiggle of every
coast, which read heavy and ugly (user design review, 2026-08-17/18).
The frame instead sits >=~600m offshore at every coast, touches land
only where coverage genuinely ends on land (the Queens->Nassau and
Bronx->Westchester borders), skims the NY/NJ state line through the
narrow channels (Kill Van Kull, Arthur Kill, the Hudson), runs one
straight line across the Lower Bay (Rockaway tip -> Great Kills), and
threads the Ellis Island / Liberty State Park gap. The frontend dims
everything outside it with a two-step feathered fade and draws a soft
dashed line on the frame itself.

Recipe: frame = simplify( close( coverage.buffer(OFFSHORE_M) UNION
shape_extra ) INTERSECT clip ), where `shape_extra` and `clip` are
STATIC political geometry committed in server/frame_inputs.json
(generated by data/audits/2026-08-18/build_frame_inputs.py -- borough
land + jurisdiction water + three user-designed corridors; see that
script's docstring for every choice). The morphological closing
(+/-CLOSE_M) merges the per-component blobs across the Narrows and
Buttermilk Channel so the frame reads as ONE region, not per-borough
bubbles.

All buffering/measuring in METRIC_CRS, all inputs/outputs lon/lat --
the dual-CRS rule.
"""

import json
import logging
from functools import lru_cache
from pathlib import Path

from pyproj import Transformer
from shapely.geometry import LineString, Polygon
from shapely.ops import transform, unary_union

from pipeline.graph.centerline import METRIC_CRS

logger = logging.getLogger(__name__)

FRAME_INPUTS_PATH = Path(__file__).parent / "frame_inputs.json"

# How far offshore the frame sits from the coverage itself. Big enough
# that it never reads as hugging a coastline; the land-clearance union
# inside frame_inputs.json guarantees >=300m off every NYC coast even
# where coverage is inset from the shore (Fresh Kills, Breezy Point tip).
OFFSHORE_M = 600.0

# Morphological closing radius: merges the buffered components across the
# widest internal water gap that must read as one region (the Narrows,
# ~1.8km between coverage edges). Closing bridges gaps up to ~2x this.
CLOSE_M = 1300.0

# Post-clip simplification -- calm, low-point-count line for the frontend.
SIMPLIFY_M = 50.0

# The feathered dim's two outward steps, measured from the frame: the
# outside dim fades in over ~FEATHERS_M[-1] instead of starting hard at
# the line (chosen from the 2026-08-18 mockup review, variant G).
FEATHERS_M = (350.0, 800.0)

# Part of the coverage-cache fingerprint (graph_store._tiles_fingerprint):
# any change to the recipe must invalidate cached frames.
FRAME_PARAMS = f"frame:v1|off:{OFFSHORE_M}|close:{CLOSE_M}|simp:{SIMPLIFY_M}|feath:{FEATHERS_M}"

_TO_M = Transformer.from_crs("EPSG:4326", METRIC_CRS, always_xy=True).transform
_TO_LL = Transformer.from_crs(METRIC_CRS, "EPSG:4326", always_xy=True).transform


def _polys_from_coords(coords) -> list[Polygon]:
    return [Polygon(rings[0], rings[1:]) for rings in coords]


@lru_cache(maxsize=1)
def _inputs_m() -> tuple:
    """(clip, shape_extra) as METRIC_CRS geometries, loaded once per
    process from the committed inputs file."""
    payload = json.loads(FRAME_INPUTS_PATH.read_text())
    clip = transform(_TO_M, unary_union(_polys_from_coords(payload["clip"])))
    extra = transform(_TO_M, unary_union(_polys_from_coords(payload["shape_extra"])))
    return clip, extra


def _ring_coords(geom) -> list[list[list[float]]]:
    """Exterior rings only: the frame is drawn as line + mask holes, and
    a hole in the FRAME (fully-enclosed foreign area -- none exist today)
    would need its own design conversation before being drawn."""
    if geom.is_empty:
        return []
    polys = geom.geoms if hasattr(geom, "geoms") else [geom]
    return [
        [[round(x, 6), round(y, 6)] for x, y in p.exterior.coords]
        for p in polys if p.geom_type == "Polygon"
    ]


def build_frame(coverage_rings: list[list[list[float]]]) -> dict:
    """The frame + its two feather rings, from the live coverage rings
    (closed [lon, lat] rings, as graph_store._compute_coverage_rings
    produces). Returns {"frame": rings, "feather_350": rings,
    "feather_800": rings} in lon/lat.

    buffer(0) on each incoming ring polygon repairs any self-touches the
    ring simplification upstream may have left -- shapely unions require
    valid geometry.
    """
    coverage_m = unary_union([
        Polygon(transform(_TO_M, LineString(ring)).coords).buffer(0)
        for ring in coverage_rings
    ])
    clip_m, extra_m = _inputs_m()

    frame_m = (
        unary_union([coverage_m.buffer(OFFSHORE_M), extra_m])
        .buffer(CLOSE_M).buffer(-CLOSE_M)
        .intersection(clip_m)
        .simplify(SIMPLIFY_M)
    )

    result = {"frame": _ring_coords(transform(_TO_LL, frame_m))}
    for dist in FEATHERS_M:
        feathered = frame_m.buffer(dist).simplify(SIMPLIFY_M)
        result[f"feather_{int(dist)}"] = _ring_coords(transform(_TO_LL, feathered))

    logger.info(
        f"[coverage_frame] frame: {len(result['frame'])} ring(s), "
        f"{sum(len(r) for r in result['frame'])} points"
    )
    return result
